### ISSUE TITLE
`Multispeciesgrowthexchange` not present at the menu bar 

### ISSUE THREAD

**Issue by hariszaf** [segrelab/comets-manual#2]
Hi there. 

Just for your information, the `Multispeciesgrowthexchange` documentation page is accessible trough the documentation site but it's not present in the menu bar. 

![image](https://user-images.githubusercontent.com/33932522/204615199-84507a91-7332-40ac-bac2-976ff10d331f.png)

**Comment by dukovski** [comment]
Thank you for pointing this out. I will fix it. 

Thanks,
Ilija

**Comment by dukovski** [comment]
Done! Thanks.
